version: '2'
services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle:/bundle
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
  cron:
    build: .
    volumes:
      - .:/app
      - bundle:/bundle
    command: bin/start-cron
volumes:
  bundle:
